name: Dataform Compilation and Deployment
 
on:
  push:
    branches: [quickstart_workspace]
 
jobs:
  compile-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g @dataform/cli
      - run: gcloud auth activate-service-account --key-file ${{ secrets.GCP_SA_KEY }}
      - run: dataform compile
      - run: dataform deploy
        env:
          DATAFORM_PROJECT_ID: your-gcp-project-id
          DATAFORM_WORKFLOW_ID: your-dataform-workflow-id
